spring.application.name=hotelInfo
server.port=8092

# 1. H2
spring.datasource.url=jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. JPA
spring.jpa.hibernate.ddl-auto=create-drop

# 3. Liquibase
spring.liquibase.enabled=false
